name: ${project.name}
version: ${project.version} (Build ${git.commit.id.abbrev}, ${git.commit.time})
description: ${project.description}
author: DoctorDark
main: org.ipvp.hcfextra.HCFExtra
commands:
  coords:
    description: Shows co-ordinates for events.
  endportal:
    description: Lights up end-portals properly.
  inv:
    aliases: [invrestore, restoreinv]
    description: Restore player inventories from last death.
  help:
    aliases: ["?"]
    description: Find out more about this server.
  hcfextra:
    description: Manage this plugin.